In [1]:
import numpy as np

In [3]:
np.__version__

'2.5.1'

## Create & Read

#### 1D Array

In [4]:
arr1 = np.array([1,2,3,4,5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [9]:
arr1.dtype

dtype('int64')

In [10]:
arr1.ndim

1

In [11]:
arr1.size


5

#### 2D Array

In [14]:
arr2 = np.array([[1,4,5],
                 [6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 3)

In [18]:
arr2.dtype

dtype('int64')

In [19]:
arr2.size

6

#### 3D array

In [23]:
arr3 = np.array([[[1,4,5],
                 [6,7,4]],[[5,8,7],[3,5,4]]])
arr3

#[2D,2D,...] == 3D

array([[[1, 4, 5],
        [6, 7, 4]],

       [[5, 8, 7],
        [3, 5, 4]]])

In [24]:
arr3.ndim

3

In [25]:
arr3.shape

(2, 2, 3)

In [26]:
arr3.size

12

#### Create Random Array

In [28]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.06013009, 0.6311981 , 0.68274418],
        [0.84800389, 0.90906359, 0.15580259]],

       [[0.40078512, 0.83268353, 0.94670415],
        [0.69315954, 0.06188715, 0.13878879]],

       [[0.81363107, 0.00603675, 0.33721749],
        [0.25605795, 0.7385143 , 0.62912234]]])

In [30]:
randomArr.dtype

dtype('float64')

In [31]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
zeroes.ndim

3

In [34]:
full = np.full((3,2,3),8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [36]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[5, 8, 7],
        [3, 5, 4]]])

In [38]:
arr3[0][0][0]

np.int64(1)

In [39]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[5, 8, 7],
        [3, 5, 4]]])

In [40]:
arr3[-1]

array([[5, 8, 7],
       [3, 5, 4]])

In [42]:
arr3[1,0,0]

np.int64(5)

In [43]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [44]:
a2

array([[[0.71132332, 0.85264265],
        [0.07173354, 0.63085975],
        [0.33116808, 0.58946199]],

       [[0.46516288, 0.24481561],
        [0.17532879, 0.88722524],
        [0.68574263, 0.39252453]]])

In [45]:
a1

array([[[0.45538994, 0.22273485],
        [0.42719456, 0.90969369],
        [0.51876786, 0.46312383]],

       [[0.91681498, 0.05169543],
        [0.75445086, 0.21209438],
        [0.19070562, 0.17291191]]])

#### Basic Math Operations

In [46]:
np.add(a1,a2)

array([[[1.16671326, 1.0753775 ],
        [0.49892809, 1.54055345],
        [0.84993594, 1.05258583]],

       [[1.38197785, 0.29651104],
        [0.92977965, 1.09931962],
        [0.87644825, 0.56543644]]])

In [47]:
np.subtract(a1,a2)

array([[[-0.25593339, -0.6299078 ],
        [ 0.35546102,  0.27883394],
        [ 0.18759978, -0.12633816]],

       [[ 0.4516521 , -0.19312017],
        [ 0.57912208, -0.67513086],
        [-0.495037  , -0.21961263]]])

In [48]:
np.divide(a1,a2)

array([[[0.64020105, 0.26122884],
        [5.95529745, 1.44199037],
        [1.56647907, 0.78567208]],

       [[1.97095475, 0.21116069],
        [4.30306332, 0.23905359],
        [0.27810087, 0.44051235]]])

In [49]:
np.multiply(a1,a2)

array([[[0.32392948, 0.18991323],
        [0.03064418, 0.57388914],
        [0.17179936, 0.2729939 ]],

       [[0.42646829, 0.01265585],
        [0.13227695, 0.18817549],
        [0.13077498, 0.06787216]]])

#### Statistical operations

In [50]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
max = np.max(a2)

In [51]:
sqrt

np.float64(5.0)

In [52]:
abs

np.int64(2)

In [53]:
power

np.int64(256)

In [54]:
log

np.float64(3.2188758248682006)

In [55]:
mins

np.float64(0.05169543179060865)

In [56]:
max

np.float64(0.8872252425774706)

#### Update the value

In [57]:
arr3


array([[[1, 4, 5],
        [6, 7, 4]],

       [[5, 8, 7],
        [3, 5, 4]]])

In [58]:
arr3[0,0,2] = 500

In [59]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  5,   8,   7],
        [  3,   5,   4]]])

In [60]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  5,   7,   8],
        [  3,   4,   5]]])

In [61]:
arr3.shape

(2, 2, 3)

In [64]:
arr3_reshape = arr3.reshape((1,,3))
arr3_reshape

ValueError: cannot reshape array of size 12 into shape (1,3,3)

#### Appending & Inserting

In [67]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [69]:
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
appd = np.append(zeroes,new_array,axis=1)  #axis 0= row,axis 1= column
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
appd.ndim

3

In [77]:
appd.shape()

TypeError: 'tuple' object is not callable

In [78]:
appd.shape

(3, 4, 3)

In [79]:
#insert

In [80]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
inserted_array = np.insert(zeroes,1,new_array,axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [85]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.1725604 , 0.26943906, 0.58640616],
        [0.98010321, 0.58876864, 0.40956164]],

       [[0.90162988, 0.78056278, 0.12274833],
        [0.48736923, 0.10041669, 0.94739623]],

       [[0.82325552, 0.14309443, 0.25092325],
        [0.85225491, 0.53084975, 0.18311638]]])

In [88]:
# delete the array
arr5=np.delete(arr4,0,axis=1)
arr5

array([[[0.98010321, 0.58876864, 0.40956164]],

       [[0.48736923, 0.10041669, 0.94739623]],

       [[0.85225491, 0.53084975, 0.18311638]]])

In [89]:
np.save("new_array",arr5)

In [90]:
np.load("new_array.npy")

array([[[0.98010321, 0.58876864, 0.40956164]],

       [[0.48736923, 0.10041669, 0.94739623]],

       [[0.85225491, 0.53084975, 0.18311638]]])